config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'moos#index'
    get 'moos/new'
    get 'moos/show'
    get 'moos/edit'
    resources :moos 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moo.rb
class Moo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/moos_controller.rb
class MoosController < ApplicationController

    def index

        @moo = Moo.all

    end

    def new

        @moo = Moo.new

    end

    def create

        @moo = Moo.create(moo_params)

        redirect_to moo_path(@moo.id)
      
    end

    def show

        @moo = Moo.find(params[:id])

    end
    
    def edit

        @moo = Moo.find(params[:id])

    end
    
    def update

        @moo = Moo.find(params[:id])

        @moo.update(moo_params)

        redirect_to moo_path(@moo.id)

    end
    
    def destroy

        @moo = Moo.find(params[:id])

        @moo.destroy

        redirect_to moos_path

    end

    private

    def moo_params

        params.require(:moo).permit(:classes, :description, :lessons, :content)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moos_helper.rb
module MoosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOOCademy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moos/edit.html.erb
<h1>Editer le cour</h1>

<%= form_for @moo do |f| %>

  <div>

     <label>Titre du cour</label>

     <%= f.text_field :classes %>

  </div>

  <div>

     <label>Description du cour</label>

     <%= f.text_area :description %>

  </div>

  <div>

     <button type="submit" >Créer le cour</button>

  </div>

  <%= link_to 'Clique pour détruire', @moo, method: :delete %>

<% end %>

app/views/moos/index.html.erb
<h1>MOOCademy</h1>

<p>Les cours c'est peut être important ?</p>

<% @moo.each do |moo| %>

    <h1><%= moo.classes %></h1>

    <p><%= moo.description %></p>

    <a href="<%= moo_path(moo.id) %>" data-method="delete" >Supprimer</a>

<% end %>

<p>

    <a href="<%= new_moo_path %>" >Créer un cour</a>

</p>

app/views/moos/new.html.erb
<h1>Créer un Cour</h1>

<%= form_for @moo do |f| %>

  <div>

      <label>Titre du cour</label>

      <%= f.text_field :classes %>

  </div>

  <div>

      <label>Description du cour</label>

      <%= f.text_area :description %>

  </div>

  <div>

      <button type="submit" >Créer le cour</button>

  </div>

<% end %>

app/views/moos/show.html.erb
<h1><%= @moo.classes %></h1>


<p><%= @moo.description %></p>

<p>

    <a href="<%= edit_moo_path(@moo.id) %>" >éditer le cour</a>

</p>

<p>

    <a href="<%= moos_path %>" >revenir aux cours</a>

</p>